language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
	
script: ./tests.sh

before_install:
  - eval "${MATRIX_EVAL}"
  - g++ -v
  - chmod 755 tests.sh
  - sudo apt-get update -qq
  - sudo apt-get install libgtest-dev google-mock cmake
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev qt5-default qttools5-dev-tools
  - sudo apt-get update
  - sudo apt-get install libboost-dev
  - chmod 755 ci/build_gtest.sh
  - sudo ci/build_gtest.sh
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  # Codecov
  - sudo pip install codecov

after_success:
  # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory lib --directory  gui --capture --no-external --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --remove coverage.info '3rd_party/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
